rsylog: Prefix header inclusion with grammar
A few headers actually live in the grammar subdirectory. If not all
magic happens properly, we get compilation failures such as:

glbl.h:37:10: fatal error: rainerscript.h: No such file or directory
   37 | #include "rainerscript.h"
      |          ^~~~~~~~~~~~~~~~

The abomination that was used to generate this diff was the following:

for _header in grammar/*.h; do find . -iname '*.[chl]' -exec sed -i "s|#include \"${_header#grammar/}\"|#include \"${_header}\"|g" {} \; ; done

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>