imhiredis: Mark internal functions as static
The function `getRole` is an internal function, thus we should indicate
such using the `static` keyword. In newer compilers this causes compiler
errors.

imhiredis.c:720:13: error: no previous prototype for 'getRole' [-Werror=missing-prototypes]
  720 | redisReply *getRole(redisContext *c) {
      |             ^~~~~~~

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>