rsylog: Prefix header inclusion with runtime
A few headers actually live in the runtime subdirectory. If not all
magic happens properly, we get compilation failures such as:

rainerscript.h:23:10: fatal error: typedefs.h: No such file or directory
   23 | #include <typedefs.h>
      |          ^~~~~~~~~~~~

rainerscript.c:42:10: fatal error: conf.h: No such file or directory
   42 | #include "conf.h"
      |          ^~~~~~~~

lexer.l:39:10: fatal error: srUtils.h: No such file or directory
   39 | #include <sys/types.h>
      |          ^~~~~~~~~~~

lexer.l:38:10: fatal error: rsyslog.h: No such file or directory
   38 | #include <ctype.h>
      |          ^~~~~~~~

../action.h:28:10: fatal error: syslogd-types.h: No such file or directory
   28 | #include "syslogd-types.h"
      |          ^~~~~~~~~~~~~~~~~

The following `sed` scripts where used to do the modification, with a
few whitespace fixes during `git add` to keep alignment nice.

for _header in runtime/*.h; do find . -iname '*.[chl]' -exec sed -i "s|#include \"${_header#runtime/}\"|#include \"${_header}\"|g" {} \; ; done
find . -iname '*.[chl]' -exec sed -i 's|#include \"conf\.h\"|#include \"runtime/conf\.h\"|g' {} \;
find . -iname '*.[chl]' -exec sed -i 's|#include \"rsyslog\.h\"|#include\"runtime/rsyslog\.h\"|g' {} \;
find . -iname '*.[chl]' -exec sed -i 's|#include \"srUtils\.h\"|#include \"runtime/srUtils\.h\"|g' {} \;
find . -iname '*.[chl]' -exec sed -i 's|#include \"typedefs\.h\"|#include \"runtime/typedefs\.h\"|g' {} \;
find . -iname '*.[chl]' -exec sed -i 's|#include \"syslogd-types\.h\"|#include \"runtime/syslogd-types\.h\"|g' {} \;

While here, the global namespaced `<typedefs.h>` was removed from
`rainerscript.c`.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>