msg: Descope iOffs variable
The iOffs variable has to big of a scope, causing compilation errors in
certain cases.

msg.c:3537:8: error: unused variable 'iOffs' [-Werror=unused-variable]
 3537 |  short iOffs;
      |        ^~~~~

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>