imhiredis: Properly mark string array as const
The string array `redis_replies` should be a const, not doing so causes
compiler errors in modern compilers.

imhiredis.c:127:33: error: initialization discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  127 | static char *redis_replies[] = {"unknown", "string", "array", "integer", "nil", "status", "error"};
      |

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>