omfile-hardened: Ensure proper includes are present
Not including `rsconf.h` causes in certain configurations to miss a
redirected include. Make sure to include everything that is used, to
avoid compilation errors such as:

omfile-hardened.c: In function 'janitorChkDynaFiles':
omfile-hardened.c:1005:45: error: invalid use of incomplete typedef 'rsconf_t' {aka 'struct rsconf_s'}
 1005 |    pCache[i]->nInactive += runModConf->pConf->globals.janitorInterval;
      |

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>