imhiredis: Do not assign values to NULL pointer
When `createRedisNode` gets called without a valid `root` pointer, we
should not assign anything to it, as we'd try to dereference a NULL
pointer. Not doing so, causes compiler errors on modern compilers.

imhiredis.c: In function 'redisGetServersList':
imhiredis.c:1425:9: error: null pointer dereference [-Werror=null-dereference]

 1425 |   *root = node;
      |   ~~~~~~^~~~~~

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>